Repository protocol/web3-dev-team, pull requests merged in 2021-06, with the labels that each got.

#86 Download migrations over IPFS
  proposals/migrate-over-ipfs.md
Labels: Steward Priority, confidence:low, ease:high, impact:high

#84 Dealbot
  proposals/images/bot-arch.png
  proposals/storage-and-retrieval-bots.md
Labels: Bedrock, confidence:high, impact:high

#80 Proposal: Lotus / Filecoin RPC and Library Audit
  proposals/80-lotus-api-audit.md
Labels: ease:high, impact:high

#79 Proposal: TypeScript Definitions for core libraries
  proposals/79-typescript-definitions.md
Labels: confidence:high, ease:high, impact:high

#111 Proposal: nft.storage Chunked CAR Uploads
  proposals/nft.storage-chunked-car-uploads.md
Labels: Nitro

#31 Proposal: IPFS Content Providing
  proposals/ipfs-content-providing.md
Labels: Steward Priority
